auteur = "Gabrielle Lahaie"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/uploads/pexels-andre-moura-3774895.jpg"
description = "Description"
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "/uploads/pexels-andre-moura-3774895.jpg"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Textes et scénarios de récits fictifs"
titre = "Portfolio"
