auteur = "Gabrielle Lahaie"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "pexels-monstera-6373296.jpg"
description = "Description"
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "illustration-of-book-icon-free-vector.webp"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Textes et scénarios de récits fictifs"
titre = "Portfolio"
